server.port=${PORT:8081}
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/unitrack}
spring.datasource.username=${DB_USERNAME:unitrack_user}
spring.datasource.password=${DB_PASSWORD:unitrack123}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database=postgresql
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false
    jwt.secret=${JWT_SECRET:5367566B59703373367639792F423F4528482B4D6251655468576D5A71347437}
jwt.expiration=86400000
spring.application.name=unitrack_backend
server.error.include-message=always
server.error.include-binding-errors=always

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${EMAIL_USERNAME:dalal.aditya.2456@gmail.com}
spring.mail.password=${EMAIL_PASSWORD:fjxh hjzp yjon pwgb}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true

logging.level.org.springframework.security=INFO
logging.level.com.unitrack=INFO

# ===== Google OAuth2 =====
google.client-id=${GOOGLE_CLIENT_ID:53211343073-ram5u537teqgbdqt7sln5274fqa98ele.apps.googleusercontent.com}

# ===== Super Admin =====
app.super-admin-email=${SUPER_ADMIN_EMAIL:dalal.aditya.2456@gmail.com}

# ===== CORS =====
app.cors.allowed-origins=${CORS_ALLOWED_ORIGINS:http://localhost:5173}